apiVersion: app/v1
kind: Deployment
metadata:
   name: sample-deployment
   namespace: default
spec:
  replicas: 1
  template:
    spec:
       containers:
       - name: app
         image: <docker_image>
         resources:
         requests:
         memory: "256Mi"
         cpu: "500m"
         limits:
         memory: "512Mi"
         cpu: "1"